export type JournalCategory = {
  name: string;
  exercises: string[];
};

export const journalCategories: JournalCategory[] = [
  {
    name: "Morning Routine",
    exercises: [
      "Lymphatic hops",
      "Body waves",
      "Trunk twist",
      "Dead arms",
      "Golf swing",
      "Arm swings",
      "March slaps",
      "Cossack squat",
      "Deep squat opener",
      "World best stretch opener",
      "Lunge front reach",
      "Table top toe touch",
      "Hands behind back and head touch elbow plank",
      "Kneeling diagonal stretch",
      "Leg Swing",
      "Journal Check-in",
      "Kaffee & Wasser vorbereiten",
      "Tagesfokus setzen",
    ],
  },
  {
    name: "Yoga",
    exercises: [
      "Mountain Pose",
      "Standing Forward Fold",
      "Half Lift",
      "Plank Pose",
      "Chaturanga",
      "Upward Dog",
      "Child's Pose",
      "Cat-Cow",
      "Downward Dog",
      "Low Lunge",
      "Half Split",
      "Pigeon Pose",
      "Seated Forward Fold",
      "Bridge Pose",
      "Supine Twist",
      "Happy Baby",
      "Legs Up The Wall",
      "Box Breathing",
    ],
  },
  {
    name: "Tabata",
    exercises: [
      "Burpee",
      "Mountain climber",
      "Jump squat",
      "High knees",
      "Skater hop",
      "Push-up",
      "Plank jack",
      "Rest",
    ],
  },
  {
    name: "HIT Workouts",
    exercises: [
      "Air Squat",
      "Push-Up",
      "Pull-Up",
      "Walking Lunge",
      "Kettlebell Swing",
      "Burpees",
      "Mountain climbers",
      "Jump squats",
      "Plank",
      "Sit-Up",
      "Russian Twist",
      "Farmer Carry",
      "Thruster",
      "Box Jump",
      "Run 400m",
      "Run 1 mile",
    ],
  },
  {
    name: "Running/Cardio",
    exercises: [
      "Easy run 20 min",
      "Tempo run 15 min",
      "Intervals 6x1 min fast",
      "Hill sprints 8x20s",
      "Zone 2 walk/jog 30 min",
      "Bike intervals 10x40/20",
      "Jump rope 10 min",
      "Rowing steady 20 min",
      "Norwegian 4x4 interval",
      "Aktive Erholung",
      "Sprint 10s",
      "Warm-up locker",
      "Cool-down locker",
    ],
  },
  {
    name: "Bodybuilding",
    exercises: [
      "Bench Press",
      "Incline Dumbbell Press",
      "Cable Fly",
      "Chest Dip",
      "Barbell Row",
      "One-Arm Dumbbell Row",
      "Pull-Up",
      "Lat Pulldown",
      "Seated Cable Row",
      "Deadlift",
      "Overhead Press",
      "Dumbbell Shoulder Press",
      "Lateral Raise",
      "Face Pull",
      "Rear Delt Fly",
      "Barbell Squat",
      "Front Squat",
      "Goblet Squat",
      "Romanian Deadlift",
      "Barbell Hip Thrust",
      "Bulgarian Split Squat",
      "Walking Lunge",
      "Leg Press",
      "Seated Leg Curl",
      "Leg Extension",
      "Standing Calf Raise",
      "Dumbbell Curl",
      "Barbell Curl",
      "Hammer Curl",
      "Triceps Dip",
      "Skull Crusher",
      "Cable Triceps Pushdown",
      "Plank",
      "Cable Crunch",
      "Hanging Leg Raise",
    ],
  },
];

export const exerciseMuscleGroupMap: Record<string, string> = {
  "Lymphatic hops": "Cardio",
  "Body waves": "Mobility",
  "Trunk twist": "Core",
  "Dead arms": "Shoulders",
  "Golf swing": "Core",
  "Arm swings": "Shoulders",
  "March slaps": "Cardio",
  "Cossack squat": "Legs",
  "Deep squat opener": "Legs",
  "World best stretch opener": "Mobility",
  "Lunge front reach": "Legs",
  "Table top toe touch": "Core",
  "Hands behind back and head touch elbow plank": "Core",
  "Kneeling diagonal stretch": "Mobility",
  "Leg Swing": "Mobility",
  "Journal Check-in": "Mobility",
  "Kaffee & Wasser vorbereiten": "Mobility",
  "Tagesfokus setzen": "Mobility",

  "Child's Pose": "Mobility",
  "Mountain Pose": "Mobility",
  "Standing Forward Fold": "Mobility",
  "Half Lift": "Mobility",
  "Plank Pose": "Core",
  Chaturanga: "Chest",
  "Upward Dog": "Mobility",
  "Cat-Cow": "Mobility",
  "Downward Dog": "Mobility",
  "Low Lunge": "Legs",
  "Half Split": "Legs",
  "Pigeon Pose": "Mobility",
  "Seated Forward Fold": "Mobility",
  "Bridge Pose": "Core",
  "Supine Twist": "Core",
  "Happy Baby": "Mobility",
  "Legs Up The Wall": "Mobility",
  "Box Breathing": "Cardio",

  Burpee: "Cardio",
  "Mountain climber": "Cardio",
  "Jump squat": "Legs",
  "High knees": "Cardio",
  "Skater hop": "Legs",
  "Push-up": "Chest",
  "Plank jack": "Core",
  Rest: "Cardio",

  "Air Squat": "Legs",
  "Push-Up": "Chest",
  "Walking Lunge": "Legs",
  "Kettlebell Swing": "Legs",
  Burpees: "Cardio",
  "Mountain climbers": "Cardio",
  "Jump squats": "Legs",
  Plank: "Core",
  "Sit-Up": "Core",
  "Russian Twist": "Core",
  "Farmer Carry": "Back",
  Thruster: "Legs",
  "Box Jump": "Legs",
  "Run 400m": "Cardio",
  "Run 1 mile": "Cardio",

  "Easy run 20 min": "Cardio",
  "Tempo run 15 min": "Cardio",
  "Intervals 6x1 min fast": "Cardio",
  "Hill sprints 8x20s": "Cardio",
  "Zone 2 walk/jog 30 min": "Cardio",
  "Bike intervals 10x40/20": "Cardio",
  "Jump rope 10 min": "Cardio",
  "Rowing steady 20 min": "Cardio",
  "Norwegian 4x4 interval": "Cardio",
  "Aktive Erholung": "Cardio",
  "Sprint 10s": "Cardio",
  "Warm-up locker": "Cardio",
  "Cool-down locker": "Cardio",

  "Bench Press": "Chest",
  "Incline Dumbbell Press": "Chest",
  "Cable Fly": "Chest",
  "Chest Dip": "Chest",
  "Barbell Row": "Back",
  "One-Arm Dumbbell Row": "Back",
  "Pull-Up": "Back",
  "Lat Pulldown": "Back",
  "Seated Cable Row": "Back",
  Deadlift: "Back",
  "Overhead Press": "Shoulders",
  "Dumbbell Shoulder Press": "Shoulders",
  "Lateral Raise": "Shoulders",
  "Face Pull": "Shoulders",
  "Rear Delt Fly": "Shoulders",
  "Barbell Squat": "Legs",
  "Front Squat": "Legs",
  "Goblet Squat": "Legs",
  "Romanian Deadlift": "Legs",
  "Barbell Hip Thrust": "Legs",
  "Bulgarian Split Squat": "Legs",
  "Leg Press": "Legs",
  "Seated Leg Curl": "Legs",
  "Leg Extension": "Legs",
  "Standing Calf Raise": "Legs",
  "Dumbbell Curl": "Arms",
  "Barbell Curl": "Arms",
  "Hammer Curl": "Arms",
  "Triceps Dip": "Arms",
  "Skull Crusher": "Arms",
  "Cable Triceps Pushdown": "Arms",
  "Cable Crunch": "Core",
  "Hanging Leg Raise": "Core",
};
